# Generated by Django 6.0.6 on 2026-06-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Lavozim Nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Lavozim kodi/slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lavozim Tavsifi')),
                ('show_in_diagram', models.BooleanField(default=False, verbose_name="Diagrammada ko'rinishi")),
                ('is_default', models.BooleanField(default=False, verbose_name='Standart lavozim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('full_name', models.CharField(max_length=150, verbose_name="To'liq ism")),
                ('role', models.CharField(choices=[('boss', 'Boss'), ('admin', 'Admin'), ('manager', 'Manager'), ('worker', 'Worker')], default='worker', max_length=20, verbose_name='Rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Rasm')),
                ('branch', models.CharField(choices=[('ichki_dokon', "Ichki Do'kon"), ('tashqi_dokon', "Tashqi Do'kon"), ('buxgalter', 'Buxgalter'), ('personal', 'Personal')], default='ichki_dokon', max_length=50, verbose_name="Bo'lim")),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Oylik ish haqi')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balans')),
                ('work_start_time', models.TimeField(blank=True, null=True, verbose_name='Ish boshlash vaqti (Shaxsiy)')),
                ('work_end_time', models.TimeField(blank=True, null=True, verbose_name='Ish tugash vaqti (Shaxsiy)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='account.lavozim', verbose_name="Bo'lim (ForeignKey)")),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
