# Generated by Django 6.0.6 on 2026-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_replace_superadmin_with_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
