# Generated by Django 6.0.6 on 2026-06-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balans'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='branch',
            field=models.CharField(choices=[('ichki_dokon', "Ichki Do'kon"), ('tashqi_dokon', "Tashqi Do'kon"), ('personal', 'Personal')], default='ichki_dokon', max_length=50, verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Oylik ish haqi'),
        ),
    ]
