# Generated by Django 6.0.6 on 2026-06-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usermodel_balance_usermodel_branch_usermodel_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Bo'lim nomi")),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Bo'lim kodi")),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='account.department', verbose_name="Bo'lim (ForeignKey)"),
        ),
    ]
