# Generated by Django 6.0.6 on 2026-06-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_seed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ish tugash vaqti (Shaxsiy)'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ish boshlash vaqti (Shaxsiy)'),
        ),
    ]
