# Generated by Django 6.0.6 on 2026-06-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usermodel_work_end_time_usermodel_work_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='branch',
            field=models.CharField(choices=[('ichki_dokon', "Ichki Do'kon"), ('tashqi_dokon', "Tashqi Do'kon"), ('buxgalter', 'Buxgalter'), ('personal', 'Personal')], default='ichki_dokon', max_length=50, verbose_name="Bo'lim"),
        ),
    ]
