# Generated by Django 6.0.6 on 2026-06-26 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Muddati')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Topshirilgan xodim')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=5, verbose_name='Baholash balli (1-5)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Baholagan rahbar')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Baholangan xodim')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='task_and_assessment.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
