# Generated by Django 6.0.6 on 2026-06-22 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hudud nomi')),
                ('latitude', models.FloatField(verbose_name='Kenglik (latitude)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (longitude)')),
                ('radius_meters', models.PositiveIntegerField(default=100, verbose_name='Radius (metr)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Ish hududi',
                'verbose_name_plural': 'Ish hududlari',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('distance_meters', models.FloatField(verbose_name='Masofa (metr)')),
                ('face_verified', models.BooleanField(default=False, verbose_name='Yuz tasdiqlandi')),
                ('location_verified', models.BooleanField(default=False, verbose_name='Joylashuv tasdiqlandi')),
                ('is_success', models.BooleanField(default=False, verbose_name='Muvaffaqiyatli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField(verbose_name='Yuz encoding (128 float)')),
                ('photo', models.ImageField(upload_to='faces/', verbose_name='Yuz rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuz profili',
                'verbose_name_plural': 'Yuz profillari',
            },
        ),
    ]
