# Generated by Django 6.0.6 on 2026-06-28 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hudud nomi')),
                ('latitude', models.FloatField(verbose_name='Kenglik (latitude)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (longitude)')),
                ('radius_meters', models.PositiveIntegerField(default=100, verbose_name='Radius (metr)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Ish hududi',
                'verbose_name_plural': 'Ish hududlari',
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField(verbose_name='Yuz encoding (128 float)')),
                ('photo', models.ImageField(upload_to='faces/', verbose_name='Yuz rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuz profili',
                'verbose_name_plural': 'Yuz profillari',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Ish boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Ish tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('departments', models.ManyToManyField(related_name='work_schedules', to='account.lavozim', verbose_name="Bo'limlar")),
            ],
            options={
                'verbose_name': 'Ish vaqti jadvali',
                'verbose_name_plural': 'Ish vaqti jadvallari',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Kirish vaqti')),
                ('check_in_success', models.BooleanField(default=True, verbose_name='Kirish muvaffaqiyatli')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Chiqish vaqti')),
                ('check_out_success', models.BooleanField(blank=True, null=True, verbose_name='Chiqish muvaffaqiyatli')),
                ('is_late', models.BooleanField(default=False, verbose_name='Kechikdimi')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'unique_together': {('worker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Kirish vaqti')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Chiqish vaqti')),
                ('is_late', models.BooleanField(default=False, verbose_name='Kechikdimi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kunlik davomat',
                'verbose_name_plural': 'Kunlik davomatlar',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
