# Generated by Django 6.0.6 on 2026-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('in', 'Kirish (In)'), ('out', 'Chiqish (Out)')], default='in', max_length=10, verbose_name='Davomat turi'),
        ),
    ]
