# Generated by Django 6.0.6 on 2026-06-30 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_fix_attendance_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='excuse_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Sabab izohi'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_excused',
            field=models.BooleanField(default=False, verbose_name='Sababli (Uzrli) kelmagan'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
    ]
