# Generated by Django 6.0.6 on 2026-06-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_attendance_attendance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='Urinishlar soni'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Manzil'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Kechikdimi'),
        ),
    ]
