# Generated by Django 6.0.6 on 2026-06-27 20:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_seed_departments'),
        ('inspection', '0003_attendance_attempts_attendance_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Ish boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Ish tugash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('departments', models.ManyToManyField(related_name='work_schedules', to='account.department', verbose_name="Bo'limlar")),
            ],
            options={
                'verbose_name': 'Ish vaqti jadvali',
                'verbose_name_plural': 'Ish vaqti jadvallari',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Kirish vaqti')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Chiqish vaqti')),
                ('is_late', models.BooleanField(default=False, verbose_name='Kechikdimi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kunlik davomat',
                'verbose_name_plural': 'Kunlik davomatlar',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
